# Generated by Django 3.2.2 on 2021-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='college',
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin',
            field=models.CharField(default='sssdx', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.CharField(default='dddd', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.CharField(default='ddd', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
